apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marketpulse-dev

resources:
- ../../base

patches:
- path: patches/replicas.yaml
- path: patches/resources.yaml
- path: patches/configmap.yaml

images:
- name: marketpulseai/frontend
  newTag: dev
- name: marketpulseai/backend
  newTag: dev
