apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketpulse-backend
  labels:
    app: marketpulse-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marketpulse-backend
  template:
    metadata:
      labels:
        app: marketpulse-backend
    spec:
      containers:
      - name: backend
        image: marketpulseai/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: marketpulse-config
              key: NODE_ENV
        - name: PORT
          value: "3000"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: marketpulse-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: marketpulse-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: marketpulse-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: marketpulse-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: marketpulse-config
              key: DB_NAME
        - name: SUPABASE_URL
          valueFrom:
            configMapKeyRef:
              name: marketpulse-config
              key: SUPABASE_URL
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: marketpulse-secrets
              key: SUPABASE_ANON_KEY
        - name: SUPABASE_SERVICE_KEY
          valueFrom:
            secretKeyRef:
              name: marketpulse-secrets
              key: SUPABASE_SERVICE_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: marketpulse-secrets
              key: JWT_SECRET
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      terminationGracePeriodSeconds: 30
