apiVersion: v1
kind: ConfigMap
metadata:
  name: marketpulse-config
data:
  NODE_ENV: "production"
  DB_HOST: "marketpulse-postgres"
  DB_PORT: "5432"
  DB_NAME: "marketpulse"
  FRONTEND_API_URL: "https://api.marketpulse.ai/api/v1"
  SUPABASE_URL: "https://your-supabase-project.supabase.co"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  01-init.sql: |
    -- Gebruikers tabel
    CREATE TABLE IF NOT EXISTS users (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        email VARCHAR(255) UNIQUE NOT NULL,
        password_hash VARCHAR(255) NOT NULL,
        full_name VARCHAR(255),
        role VARCHAR(50) NOT NULL DEFAULT 'user',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

    -- Platforms tabel
    CREATE TABLE IF NOT EXISTS platforms (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        name VARCHAR(100) NOT NULL,
        type VARCHAR(50) NOT NULL,
        api_credentials JSONB,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

    -- Analyses tabel
    CREATE TABLE IF NOT EXISTS analyses (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id UUID REFERENCES users(id) ON DELETE CASCADE,
        platform_id UUID REFERENCES platforms(id) ON DELETE CASCADE,
        query_parameters JSONB NOT NULL,
        status VARCHAR(50) NOT NULL DEFAULT 'pending',
        result_data JSONB,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

    -- Sentiment analyses tabel
    CREATE TABLE IF NOT EXISTS sentiment_analyses (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        analysis_id UUID REFERENCES analyses(id) ON DELETE CASCADE,
        content_id VARCHAR(255) NOT NULL,
        content_text TEXT NOT NULL,
        sentiment_score DECIMAL(5,2) NOT NULL,
        sentiment_magnitude DECIMAL(5,2) NOT NULL,
        sentiment_label VARCHAR(50) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

    -- Trending topics tabel
    CREATE TABLE IF NOT EXISTS trending_topics (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        analysis_id UUID REFERENCES analyses(id) ON DELETE CASCADE,
        topic VARCHAR(255) NOT NULL,
        frequency INTEGER NOT NULL,
        relevance_score DECIMAL(5,2) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

    -- Reddit posts tabel
    CREATE TABLE IF NOT EXISTS reddit_posts (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        analysis_id UUID REFERENCES analyses(id) ON DELETE CASCADE,
        post_id VARCHAR(255) NOT NULL,
        subreddit VARCHAR(255) NOT NULL,
        title TEXT NOT NULL,
        content TEXT,
        author VARCHAR(255),
        score INTEGER NOT NULL DEFAULT 0,
        num_comments INTEGER NOT NULL DEFAULT 0,
        created_utc TIMESTAMP WITH TIME ZONE,
        permalink VARCHAR(512),
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

    -- Twitter tweets tabel
    CREATE TABLE IF NOT EXISTS twitter_tweets (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        analysis_id UUID REFERENCES analyses(id) ON DELETE CASCADE,
        tweet_id VARCHAR(255) NOT NULL,
        content TEXT NOT NULL,
        author VARCHAR(255) NOT NULL,
        retweet_count INTEGER NOT NULL DEFAULT 0,
        favorite_count INTEGER NOT NULL DEFAULT 0,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        tweet_created_at TIMESTAMP WITH TIME ZONE
    );

    -- Voeg basis platforms toe
    INSERT INTO platforms (name, type) VALUES 
    ('Reddit', 'reddit'),
    ('Twitter', 'twitter'),
    ('Facebook', 'facebook'),
    ('Instagram', 'instagram'),
    ('LinkedIn', 'linkedin')
    ON CONFLICT DO NOTHING;
